version: "3"

services:
  be:
    container_name: facebookapp
    build: backend
    ports:
      - "8000:8000"
    expose:
      - 8000

  fe:
    container_name: facebook_ui
    build: frontend
    ports:
      - "4200:4200"
    expose:
      - 4200
